src/components/pharmacy/Pharmacy.tsx
src/components/ward/Ward.tsx
src/routes.tsx

Fix a bunch of imports that prevent running the app from case sensitive file systems (e.g. on Linux).
(and some random whitespace deletions because I forgot to turn off the related vim config lol)

Fix import errors due to case sensitive file system (Linux) [OP-100]

---

src/App.tsx
src/components/login/login.style.ts
src/components/login/login.tsx
src/components/patientsDatabase/PatientsDatabase.tsx
src/components/sharedComponents/PatientBasicInfoForm.tsx
src/components/sharedComponents/styles/PatientBasicInfoForm.style.ts

This Pull Request fixes the `<TextField>` behavior in the `<Login>` activity and on `<PatientBasicInfoForm>`. It was noticed that the form text field style must be generalized to avoid repetition. Beyond that, `<PatientBasicInfoForm>` demands some refactoring. The way it deals with the extra field doesn't look good, and it's hard to reuse that component that way.
Closes: [OP-142](https://openhospital.atlassian.net/browse/OP-142)

Resolve OP-142-form-field-animation

---

package-lock.json

reallign package-lock file with latest version

package-lock: update file

---

package-lock.json
package.json

Add missing browserslist to package.json

---

src/components/colleaguesDatabase/ColleagueDetails/ColleagueDetails.tsx

Avoid importing all Lodash just to use sample function. Import directly sample function from lodash instead

components / ColleagueDetails: do not import all lodash just to use sample

---

src/components/colleaguesDatabase/ColleaguesDatabase.tsx

remove key warning by adding key in colleagues list. Simulate unique id in colleagues fetching list

components / colleaguesDatabase: fix key missing warning in colleagues list

---

jest.config.js
src/shared/lib/calendar/__tests__/index.test.js
src/shared/lib/calendar/index.css
src/shared/lib/calendar/index.js

Add some improvements to calendar components:
- add basic tests
- fix key missing error for rendering arrays
- fix month labels
- use let / const
- remove deprecated componentWillMount
- fix selected day css

shared / calendar: improve component

---

src/components/ward/Ward.tsx

Ward component is broken, fix explosions

components  / Ward: fix broken component

---

package-lock.json
package.json
public/index.html
src/components/accessories/footer/styles.scss
src/components/activities/loginActivity/styles.scss
src/styles/_variables.scss
src/styles/index.scss

The code fixes some graphic bugs in the footer section and inside the Login page.

OP-267 Fix Footer responsiveness

---

package-lock.json
package.json
public/index.html
src/components/accessories/footer/styles.scss
src/components/activities/dashboardActivity/styles.scss
src/components/activities/loginActivity/styles.scss
src/styles/_variables.scss
src/styles/index.scss

The code fixes the responsiveness of the DashboardActivity buttons.

Op 301 fix dashboard activity responsiveness

---

package-lock.json
package.json
public/index.html
src/components/accessories/appHeader/AppHeader.tsx
src/components/accessories/appHeader/styles.scss
src/components/accessories/footer/styles.scss
src/components/activities/dashboardActivity/styles.scss
src/components/activities/loginActivity/styles.scss
src/styles/_variables.scss
src/styles/index.scss

The code fix some graphic bugs inside the Header component and fix the Header responsiveness. The code also add to the user the capabilities to trigger the mobile menu with an hamburger icon.

OP-300 | Fix AppHeader responsiveness

---

README.md
cypress/integration/login_activity_spec.js
src/components/accessories/appHeader/AppHeader.tsx
src/components/accessories/appHeader/styles.scss
src/components/accessories/footer/styles.scss
src/components/activities/dashboardActivity/styles.scss
src/components/activities/loginActivity/styles.scss
src/components/activities/searchPatientActivity/PatientSearchItem.tsx
src/components/activities/searchPatientActivity/SearchPatientActivity.tsx
src/components/activities/searchPatientActivity/styles.scss
src/styles/_variables.scss

The code add the responsiveness of the Search Patient Activity page and fix some graphic bugs.

OP-303 | Fix SearchPatientActivity responsiveness

---

.env.staging
package-lock.json
package.json

Create a script to override `PUBLIC_PATH`, which must have the value of `oh20` in _staging_ and _production_ environments.

OP-296 | Create env.staging and add build script

---

src/components/accessories/tabs/styles.scss
src/components/activities/patientDetailsActivity/styles.scss
src/components/activities/patientDetailsActivity/tabsConfig.tsx
src/components/activities/patientDetailsActivityContent/PatientDetailsActivityContent.tsx
src/components/activities/patientDetailsActivityContent/styles.scss
src/components/activities/patientDetailsActivityContent/types.ts

The code provides a new component called PatientDetailsActivityContent in order to wrap the tab's content.
This component takes two props: 
- title : the section's title;
- content : the JSX content (for now it's just static HTML, in the future will be a Component itself.

PatientDetailsActivity content placeholder

---

src/components/accessories/tabs/RouterTabs.tsx
src/components/accessories/tabs/types.ts
src/components/activities/patientDetailsActivity/PatientDetailsActivity.tsx
src/components/activities/patientDetailsActivity/tabsConfig.tsx

[OP-480] - implemented patient router tabs navigation
[OP-480]: https://openhospital.atlassian.net/browse/OP-480

feature(patient router tabs):[OP-480] - implemented patient router tabs navigation

---

src/components/accessories/feedback/OHFeedback.tsx

This fix the multiple calls issue when we're on patient search page. 
Resolves: OP-822

OP-822 | Fix multiple calls on patient search

---

src/components/accessories/admission/PatientAdmission.tsx
src/components/accessories/admission/PatientAdmissions.tsx
src/mockServer/fixtures/patientDTO.js

OP-835 | Add back the admission history to the Admission section

---

src/libraries/permissionUtils/Permission.tsx

Intended use:
```jsx
<Permission require="someComponent.read">
<SomeComponent />
</Permission>
```

Implement Permission component

---

docker-compose.yaml
src/components/accessories/admission/admissionTable/AdmissionTable.tsx
src/components/accessories/patientExams/consts.ts
src/components/accessories/patientOperation/consts.ts
src/components/accessories/patientTherapy/PatientTherapy.tsx
src/components/accessories/patientTherapy/consts.ts
src/components/accessories/patientTherapy/therapyForm/TherapyForm.tsx
src/components/accessories/patientTriage/patientTriageTable/PatientTriageTable.tsx
src/generated/runtime.ts
src/libraries/formDataHandling/functions.ts

Make the endDate readonly and calculation based startDate, nbDays, nbWeeks and nbMonths.

OH2-130 | Update patient therapy

---

src/components/accessories/dashboard/dashboardContent/filter/DashboardFilter.tsx
src/components/accessories/dashboard/dashboardContent/filter/usePeriodOptions.ts
src/components/accessories/dashboard/dashboardContent/styles.scss
src/components/accessories/dateField/DateField.tsx
src/components/accessories/dateField/types.ts
src/components/accessories/dateRangeField/DateRangeField.tsx
src/components/accessories/dateRangeField/types.ts
src/resources/i18n/en.json

Update charts layout and restore desktop date picker with de possibility to select a single date instead of range date.

OH2-173 | Dashboard minor fixes

---

src/components/Private.js
src/components/activities/loginActivity/LoginActivity.tsx
src/components/activities/loginActivity/styles.scss
src/index.tsx
src/resources/i18n/en.json
src/state/hospital/actions.ts

See OH2-179.
Paired with https://github.com/informatici/openhospital-api/pull/214.

OH2-179 | make get hospital public

---

src/components/accessories/opds/filter/OpdFilterForm.tsx
src/resources/i18n/en.json

Updates :
- Age min (0) and max (200);
- Disable future date;
- Set `month`, `dateFrom` and `dateTo` based on selected `year`.

OH2-184 | Update visits filter

---

src/components/accessories/opds/filter/OpdFilterForm.tsx
src/components/accessories/opds/filter/styles.scss

- Put `disease` and `diseaseType` each on a new line
- Fix 'undefined initial value' issue on fields `disease` and `diseaseType`

OHCS-97 visit function wrong text length

---

src/generated/runtime.ts

See OP-1104.
- set `withCredentials: true`
This PR is paired with https://github.com/informatici/openhospital-api/pull/283

OP-1104 Fix session audit update upon logout from UI

---

src/components/accessories/dashboard/layouts/consts.ts
src/components/accessories/dashboard/layouts/container/GridLayoutContainer.tsx

I fixed the issue on dashboard, that was causing a random behavior when user's screen change and sometimes when user navigate to the dashboard page

Fix issue on dashboard concerning random behavior when changing screen size (OH2-194)

---

src/components/activities/loginActivity/RedirectAfterLogin.tsx
src/components/activities/loginActivity/types.ts
src/customization/landingPage.ts
src/libraries/hooks/useLandingPageRoute.ts
src/mockServer/fixtures/permissionList.js
src/routes/MainRouter.tsx
src/routes/const.ts
src/types.ts

OH2-146 | Implement per-role landing page

---

src/components/accessories/dashboard/layouts/consts.ts
src/components/accessories/dashboard/layouts/container/GridLayoutContainer.tsx
src/components/accessories/dashboard/layouts/toolbox/GridLayoutToolBox.tsx

See OH2-194.
I changed the responsiveness behavior of the dashboard. Now, when a user add a widget, that widget is added for all breakpoints (screen sizes). Idem for when the user remove a widget.

OH2-194 Changed the responsiveness behavior of the dashboard

---

src/components/accessories/admission/admissionTable/AdmissionTable.tsx
src/components/accessories/billTable/BillTable.tsx
src/components/accessories/discharge/PatientDischarge.tsx
src/components/accessories/laboratory/Exams.tsx
src/components/accessories/opds/Opds.tsx
src/components/accessories/patientExams/patientExamsTable/PatientExamsTable.tsx
src/components/accessories/patientOPD/patientOPDTable/PatientOPDTable.tsx
src/components/accessories/patientOperation/operationTable/OperationRowTable.tsx
src/components/accessories/patientPicker/PatientPicker.tsx
src/components/accessories/patientTherapy/patientTherapyTable/PatientTherapyTable.tsx
src/components/accessories/patientTriage/patientTriageTable/PatientTriageTable.tsx
src/components/accessories/patientVisit/patientVisitTable/PatientVisitTable.tsx
src/components/accessories/paymentsTable/PaymentsTable.tsx
src/components/activities/searchPatientActivity/SearchPatientActivity.tsx

OH2-210 | Replace warning message for SUCCESS_EMPTY state with info message

---

src/components/accessories/discharge/dischargeForm/DischargeForm.tsx

OH2-219 | Make autocomplete fields full width in Patient Discharge form

---

src/components/accessories/patientExtraData/patientExtraData.tsx
src/components/accessories/patientExtraData/types.ts
src/components/accessories/patientSummary/PatientSummary.tsx

OH2-214 | Make all Clinic data readonly

---

src/components/activities/patientDetailsActivity/InPatientDashboardMenu.tsx
src/components/activities/patientDetailsActivity/OutPatientDashboardMenu.tsx
src/routes/Patients/PatientsDetailsRoutes.tsx

OH2-224 | Hide Therapy for both OUTPATIENT and INPATIENT

---

src/components/accessories/laboratory/Exams.tsx
src/components/activities/patientDetailsActivity/InPatientDashboardMenu.tsx
src/resources/i18n/en.json

See OH2-217.
Fix by the way non paginated query being sent on page refresh in laboratory.

OH2-217 | Change inpatient visit label to 'Consultancy'

---

src/components/accessories/hospitalInfo/HospitalInfo.tsx
src/components/accessories/hospitalInfo/styles.scss
src/components/accessories/hospitalInfo/types.ts
src/components/activities/laboratoryActivity/LaboratoryActivity.tsx
src/components/activities/patientDetailsActivity/PatientDetailsActivity.tsx
src/components/activities/visitsActivity/VisitsActivity.tsx

See OH2-228.
This add the hospital info on the top of some pages when printing.
For the moment, Hospital infos have been added on the top of pages located in the activities PatientDetails, Laboratory, Visit. 
They could be added in other pages if necessary, using the HospitalInfo component.

OH2-228 | Add hospital info on print

---

src/components/accessories/admission/admissionTable/AdmissionTable.tsx
src/components/accessories/laboratory/table/ExamTable.tsx
src/components/accessories/langSwitcher/LangSwitcher.tsx
src/components/accessories/patientExams/patientExamsTable/PatientExamsTable.tsx
src/components/accessories/patientOPD/patientOPDTable/PatientOPDTable.tsx
src/components/accessories/patientOperation/operationTable/OperationRowTable.tsx
src/components/accessories/patientSummary/patientSummaryByType/PatientSummaryByType.tsx
src/components/accessories/patientTherapy/patientTherapyTable/PatientTherapyTable.tsx
src/components/accessories/patientTriage/patientTriageTable/PatientTriageTable.tsx
src/components/accessories/patientVisit/patientVisitTable/PatientVisitTable.tsx
src/components/activities/newPatientActivity/NewPatientActivity.tsx
src/resources/i18n/en.json

- OH2-237
- OH2-235
- OH2-234
- OH2-236

OH2-237 | OH2-235 | OH2-236 | OH2-234

---

src/components/accessories/currentAdmission/CurrentAdmission.tsx
src/components/accessories/currentAdmission/currentAdmissionData/CurrentAdmissionData.tsx
src/components/accessories/currentAdmission/types.ts
src/components/accessories/discharge/PatientDischarge.tsx
src/components/accessories/discharge/dischargeForm/DischargeForm.tsx

OH2-240 | Improve discharge page

---

src/components/accessories/patientDataForm/PatientDataForm.tsx

OH2-250 | Update age field validation

---

src/components/activities/searchPatientActivity/SearchPatientActivity.tsx

OH2-261 | Fix search patient search form validation

---

src/components/accessories/autocompleteField/AutocompleteField.tsx

OH2-263 | Clear autocomplete missing value when freeSolo not freeSolo

---

src/components/accessories/admission/admissionForm/AdmissionForm.tsx
src/resources/i18n/en.json

OH2-262 | Update admission ward field validation

---

src/components/accessories/admission/admissionForm/AdmissionForm.tsx

OH2-265 | Filter wards by patient sex
